# Generated by Django 3.1.6 on 2021-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
