# Generated by Django 3.1.6 on 2021-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='avg_r',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
    ]
