# Generated by Django 3.1.6 on 2021-03-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20210306_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='shift',
            field=models.CharField(max_length=1),
        ),
    ]
