# Generated by Django 3.1.6 on 2021-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20210306_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rides',
            new_name='Ride',
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={},
        ),
    ]
