# Generated by Django 3.1.6 on 2021-03-30 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20210320_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterModelOptions(
            name='cab',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.AddField(
            model_name='cab',
            name='curr_save_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cab',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='executive',
            name='reg_city',
            field=models.CharField(default='Bengaluru', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
