# Generated by Django 3.1.6 on 2021-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20210330_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_engaged',
            field=models.BooleanField(default=False),
        ),
    ]
